export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const SET_INGREDIENTS_FETCH_FAILED = 'SET_INGREDIENTS_FETCH_FAILED';
export const SET_PRICE = 'SET_PRICE';

export const INIT_PURCHASE = 'INIT_PURCHASE';
export const START_BURGER_PURCHASE = 'START_BURGER_PURCHASE';
export const UPDATE_BURGER_PURCHASE_SUCCESS = 'UPDATE_BURGER_PURCHASE_SUCCESS';
export const UPDATE_BURGER_PURCHASE_FAILURE = 'UPDATE_BURGER_PURCHASE_FAILURE';

export const START_ORDERS_FETCH = 'START_ORDERS_FETCH';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';